version: "3.4"
services:
  indexer:
    restart: always
    build:
      context: .
      dockerfile: ./cmd/indexer/Dockerfile
    working_dir: /cmd
    depends_on:
      - pg
      - redis
    entrypoint: ./indexer
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      REDIS_ADDR: redis:6379
    ports:
      - 5001:5001
  rest:
    restart: always
    build:
      context: .
      dockerfile: ./cmd/rest/Dockerfile
    working_dir: /cmd
    depends_on:
      - indexer
    entrypoint: ./rest
    environment:
      INDEXER_ADDR: indexer:5001
    ports:
      - 8080:8080
  pg:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5627:5432
  redis:
    image: "redis:alpine"
    restart: always
volumes:
  pgdata:
