version: '3.4'
services:
  indexer:
    restart: always
    build:
      context: .
      dockerfile: ./cmd/indexer/Dockerfile
    working_dir: /cmd
    depends_on:
      - pg
    entrypoint: ./indexer
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5001:5001
  rest:
    restart: always
    build:
      context: .
      dockerfile: ./cmd/rest/Dockerfile
    working_dir: /cmd
    depends_on:
      - pg
      - indexer
    entrypoint: ./rest
    ports:
      - 8080:8080
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5627:5432
